repos:

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.0
  hooks:
  - id: mypy
    args: [--scripts-are-modules, --explicit-package-bases]
    additional_dependencies:
    - types-python-dateutil
    - types-Flask
    - types-Markdown
    - types-requests
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.3
  hooks:
  - id: ruff
